import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Navbar from '../components/Navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Typing Game",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="page-content">
          {children}
        </main>
      </body>
    </html>
  );
}
